package subscribedcatalog

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"vcd.subscribedCatalog.SubscribedCatalog",
		reflect.TypeOf((*SubscribedCatalog)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cancelFailedTasks", GoGetter: "CancelFailedTasks"},
			_jsii_.MemberProperty{JsiiProperty: "cancelFailedTasksInput", GoGetter: "CancelFailedTasksInput"},
			_jsii_.MemberProperty{JsiiProperty: "catalogVersion", GoGetter: "CatalogVersion"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "created", GoGetter: "Created"},
			_jsii_.MemberProperty{JsiiProperty: "deleteForce", GoGetter: "DeleteForce"},
			_jsii_.MemberProperty{JsiiProperty: "deleteForceInput", GoGetter: "DeleteForceInput"},
			_jsii_.MemberProperty{JsiiProperty: "deleteRecursive", GoGetter: "DeleteRecursive"},
			_jsii_.MemberProperty{JsiiProperty: "deleteRecursiveInput", GoGetter: "DeleteRecursiveInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "failedTasks", GoGetter: "FailedTasks"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "href", GoGetter: "Href"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "isLocal", GoGetter: "IsLocal"},
			_jsii_.MemberProperty{JsiiProperty: "isPublished", GoGetter: "IsPublished"},
			_jsii_.MemberProperty{JsiiProperty: "isShared", GoGetter: "IsShared"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "makeLocalCopy", GoGetter: "MakeLocalCopy"},
			_jsii_.MemberProperty{JsiiProperty: "makeLocalCopyInput", GoGetter: "MakeLocalCopyInput"},
			_jsii_.MemberProperty{JsiiProperty: "mediaItemList", GoGetter: "MediaItemList"},
			_jsii_.MemberProperty{JsiiProperty: "metadata", GoGetter: "Metadata"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "numberOfMedia", GoGetter: "NumberOfMedia"},
			_jsii_.MemberProperty{JsiiProperty: "numberOfVappTemplates", GoGetter: "NumberOfVappTemplates"},
			_jsii_.MemberProperty{JsiiProperty: "org", GoGetter: "Org"},
			_jsii_.MemberProperty{JsiiProperty: "orgInput", GoGetter: "OrgInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "ownerName", GoGetter: "OwnerName"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "publishSubscriptionType", GoGetter: "PublishSubscriptionType"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetCancelFailedTasks", GoMethod: "ResetCancelFailedTasks"},
			_jsii_.MemberMethod{JsiiMethod: "resetDeleteForce", GoMethod: "ResetDeleteForce"},
			_jsii_.MemberMethod{JsiiMethod: "resetDeleteRecursive", GoMethod: "ResetDeleteRecursive"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetMakeLocalCopy", GoMethod: "ResetMakeLocalCopy"},
			_jsii_.MemberMethod{JsiiMethod: "resetOrg", GoMethod: "ResetOrg"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetStorageProfileId", GoMethod: "ResetStorageProfileId"},
			_jsii_.MemberMethod{JsiiMethod: "resetStoreTasks", GoMethod: "ResetStoreTasks"},
			_jsii_.MemberMethod{JsiiMethod: "resetSubscriptionPassword", GoMethod: "ResetSubscriptionPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncAll", GoMethod: "ResetSyncAll"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncAllMediaItems", GoMethod: "ResetSyncAllMediaItems"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncAllVappTemplates", GoMethod: "ResetSyncAllVappTemplates"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncCatalog", GoMethod: "ResetSyncCatalog"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncMediaItems", GoMethod: "ResetSyncMediaItems"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncOnRefresh", GoMethod: "ResetSyncOnRefresh"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncVappTemplates", GoMethod: "ResetSyncVappTemplates"},
			_jsii_.MemberProperty{JsiiProperty: "runningTasks", GoGetter: "RunningTasks"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfileId", GoGetter: "StorageProfileId"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfileIdInput", GoGetter: "StorageProfileIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "storeTasks", GoGetter: "StoreTasks"},
			_jsii_.MemberProperty{JsiiProperty: "storeTasksInput", GoGetter: "StoreTasksInput"},
			_jsii_.MemberProperty{JsiiProperty: "subscriptionPassword", GoGetter: "SubscriptionPassword"},
			_jsii_.MemberProperty{JsiiProperty: "subscriptionPasswordInput", GoGetter: "SubscriptionPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "subscriptionUrl", GoGetter: "SubscriptionUrl"},
			_jsii_.MemberProperty{JsiiProperty: "subscriptionUrlInput", GoGetter: "SubscriptionUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncAll", GoGetter: "SyncAll"},
			_jsii_.MemberProperty{JsiiProperty: "syncAllInput", GoGetter: "SyncAllInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncAllMediaItems", GoGetter: "SyncAllMediaItems"},
			_jsii_.MemberProperty{JsiiProperty: "syncAllMediaItemsInput", GoGetter: "SyncAllMediaItemsInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncAllVappTemplates", GoGetter: "SyncAllVappTemplates"},
			_jsii_.MemberProperty{JsiiProperty: "syncAllVappTemplatesInput", GoGetter: "SyncAllVappTemplatesInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncCatalog", GoGetter: "SyncCatalog"},
			_jsii_.MemberProperty{JsiiProperty: "syncCatalogInput", GoGetter: "SyncCatalogInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncMediaItems", GoGetter: "SyncMediaItems"},
			_jsii_.MemberProperty{JsiiProperty: "syncMediaItemsInput", GoGetter: "SyncMediaItemsInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncOnRefresh", GoGetter: "SyncOnRefresh"},
			_jsii_.MemberProperty{JsiiProperty: "syncOnRefreshInput", GoGetter: "SyncOnRefreshInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncVappTemplates", GoGetter: "SyncVappTemplates"},
			_jsii_.MemberProperty{JsiiProperty: "syncVappTemplatesInput", GoGetter: "SyncVappTemplatesInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tasksFileName", GoGetter: "TasksFileName"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "vappTemplateList", GoGetter: "VappTemplateList"},
		},
		func() interface{} {
			j := jsiiProxy_SubscribedCatalog{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.subscribedCatalog.SubscribedCatalogConfig",
		reflect.TypeOf((*SubscribedCatalogConfig)(nil)).Elem(),
	)
}
