package orgvdc

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"vcd.orgVdc.OrgVdc",
		reflect.TypeOf((*OrgVdc)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "allocationModel", GoGetter: "AllocationModel"},
			_jsii_.MemberProperty{JsiiProperty: "allocationModelInput", GoGetter: "AllocationModelInput"},
			_jsii_.MemberProperty{JsiiProperty: "allowOverCommit", GoGetter: "AllowOverCommit"},
			_jsii_.MemberProperty{JsiiProperty: "allowOverCommitInput", GoGetter: "AllowOverCommitInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "computeCapacity", GoGetter: "ComputeCapacity"},
			_jsii_.MemberProperty{JsiiProperty: "computeCapacityInput", GoGetter: "ComputeCapacityInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "cpuGuaranteed", GoGetter: "CpuGuaranteed"},
			_jsii_.MemberProperty{JsiiProperty: "cpuGuaranteedInput", GoGetter: "CpuGuaranteedInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuSpeed", GoGetter: "CpuSpeed"},
			_jsii_.MemberProperty{JsiiProperty: "cpuSpeedInput", GoGetter: "CpuSpeedInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultComputePolicyId", GoGetter: "DefaultComputePolicyId"},
			_jsii_.MemberProperty{JsiiProperty: "defaultComputePolicyIdInput", GoGetter: "DefaultComputePolicyIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultVmSizingPolicyId", GoGetter: "DefaultVmSizingPolicyId"},
			_jsii_.MemberProperty{JsiiProperty: "defaultVmSizingPolicyIdInput", GoGetter: "DefaultVmSizingPolicyIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "deleteForce", GoGetter: "DeleteForce"},
			_jsii_.MemberProperty{JsiiProperty: "deleteForceInput", GoGetter: "DeleteForceInput"},
			_jsii_.MemberProperty{JsiiProperty: "deleteRecursive", GoGetter: "DeleteRecursive"},
			_jsii_.MemberProperty{JsiiProperty: "deleteRecursiveInput", GoGetter: "DeleteRecursiveInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "edgeClusterId", GoGetter: "EdgeClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "edgeClusterIdInput", GoGetter: "EdgeClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "elasticity", GoGetter: "Elasticity"},
			_jsii_.MemberProperty{JsiiProperty: "elasticityInput", GoGetter: "ElasticityInput"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableFastProvisioning", GoGetter: "EnableFastProvisioning"},
			_jsii_.MemberProperty{JsiiProperty: "enableFastProvisioningInput", GoGetter: "EnableFastProvisioningInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableNsxvDistributedFirewall", GoGetter: "EnableNsxvDistributedFirewall"},
			_jsii_.MemberProperty{JsiiProperty: "enableNsxvDistributedFirewallInput", GoGetter: "EnableNsxvDistributedFirewallInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableThinProvisioning", GoGetter: "EnableThinProvisioning"},
			_jsii_.MemberProperty{JsiiProperty: "enableThinProvisioningInput", GoGetter: "EnableThinProvisioningInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableVmDiscovery", GoGetter: "EnableVmDiscovery"},
			_jsii_.MemberProperty{JsiiProperty: "enableVmDiscoveryInput", GoGetter: "EnableVmDiscoveryInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "includeVmMemoryOverhead", GoGetter: "IncludeVmMemoryOverhead"},
			_jsii_.MemberProperty{JsiiProperty: "includeVmMemoryOverheadInput", GoGetter: "IncludeVmMemoryOverheadInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "memoryGuaranteed", GoGetter: "MemoryGuaranteed"},
			_jsii_.MemberProperty{JsiiProperty: "memoryGuaranteedInput", GoGetter: "MemoryGuaranteedInput"},
			_jsii_.MemberProperty{JsiiProperty: "metadata", GoGetter: "Metadata"},
			_jsii_.MemberProperty{JsiiProperty: "metadataEntry", GoGetter: "MetadataEntry"},
			_jsii_.MemberProperty{JsiiProperty: "metadataEntryInput", GoGetter: "MetadataEntryInput"},
			_jsii_.MemberProperty{JsiiProperty: "metadataInput", GoGetter: "MetadataInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkPoolName", GoGetter: "NetworkPoolName"},
			_jsii_.MemberProperty{JsiiProperty: "networkPoolNameInput", GoGetter: "NetworkPoolNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkQuota", GoGetter: "NetworkQuota"},
			_jsii_.MemberProperty{JsiiProperty: "networkQuotaInput", GoGetter: "NetworkQuotaInput"},
			_jsii_.MemberProperty{JsiiProperty: "nicQuota", GoGetter: "NicQuota"},
			_jsii_.MemberProperty{JsiiProperty: "nicQuotaInput", GoGetter: "NicQuotaInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "org", GoGetter: "Org"},
			_jsii_.MemberProperty{JsiiProperty: "orgInput", GoGetter: "OrgInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "providerVdcName", GoGetter: "ProviderVdcName"},
			_jsii_.MemberProperty{JsiiProperty: "providerVdcNameInput", GoGetter: "ProviderVdcNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putComputeCapacity", GoMethod: "PutComputeCapacity"},
			_jsii_.MemberMethod{JsiiMethod: "putMetadataEntry", GoMethod: "PutMetadataEntry"},
			_jsii_.MemberMethod{JsiiMethod: "putStorageProfile", GoMethod: "PutStorageProfile"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowOverCommit", GoMethod: "ResetAllowOverCommit"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuGuaranteed", GoMethod: "ResetCpuGuaranteed"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuSpeed", GoMethod: "ResetCpuSpeed"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultComputePolicyId", GoMethod: "ResetDefaultComputePolicyId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultVmSizingPolicyId", GoMethod: "ResetDefaultVmSizingPolicyId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetEdgeClusterId", GoMethod: "ResetEdgeClusterId"},
			_jsii_.MemberMethod{JsiiMethod: "resetElasticity", GoMethod: "ResetElasticity"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableFastProvisioning", GoMethod: "ResetEnableFastProvisioning"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableNsxvDistributedFirewall", GoMethod: "ResetEnableNsxvDistributedFirewall"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableThinProvisioning", GoMethod: "ResetEnableThinProvisioning"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableVmDiscovery", GoMethod: "ResetEnableVmDiscovery"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIncludeVmMemoryOverhead", GoMethod: "ResetIncludeVmMemoryOverhead"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryGuaranteed", GoMethod: "ResetMemoryGuaranteed"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetadata", GoMethod: "ResetMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetadataEntry", GoMethod: "ResetMetadataEntry"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkPoolName", GoMethod: "ResetNetworkPoolName"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkQuota", GoMethod: "ResetNetworkQuota"},
			_jsii_.MemberMethod{JsiiMethod: "resetNicQuota", GoMethod: "ResetNicQuota"},
			_jsii_.MemberMethod{JsiiMethod: "resetOrg", GoMethod: "ResetOrg"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmPlacementPolicyIds", GoMethod: "ResetVmPlacementPolicyIds"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmQuota", GoMethod: "ResetVmQuota"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmSizingPolicyIds", GoMethod: "ResetVmSizingPolicyIds"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfile", GoGetter: "StorageProfile"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfileInput", GoGetter: "StorageProfileInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "vmPlacementPolicyIds", GoGetter: "VmPlacementPolicyIds"},
			_jsii_.MemberProperty{JsiiProperty: "vmPlacementPolicyIdsInput", GoGetter: "VmPlacementPolicyIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmQuota", GoGetter: "VmQuota"},
			_jsii_.MemberProperty{JsiiProperty: "vmQuotaInput", GoGetter: "VmQuotaInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmSizingPolicyIds", GoGetter: "VmSizingPolicyIds"},
			_jsii_.MemberProperty{JsiiProperty: "vmSizingPolicyIdsInput", GoGetter: "VmSizingPolicyIdsInput"},
		},
		func() interface{} {
			j := jsiiProxy_OrgVdc{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.orgVdc.OrgVdcComputeCapacity",
		reflect.TypeOf((*OrgVdcComputeCapacity)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"vcd.orgVdc.OrgVdcComputeCapacityCpu",
		reflect.TypeOf((*OrgVdcComputeCapacityCpu)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.orgVdc.OrgVdcComputeCapacityCpuOutputReference",
		reflect.TypeOf((*OrgVdcComputeCapacityCpuOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "allocated", GoGetter: "Allocated"},
			_jsii_.MemberProperty{JsiiProperty: "allocatedInput", GoGetter: "AllocatedInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "limit", GoGetter: "Limit"},
			_jsii_.MemberProperty{JsiiProperty: "limitInput", GoGetter: "LimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "reserved", GoGetter: "Reserved"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllocated", GoMethod: "ResetAllocated"},
			_jsii_.MemberMethod{JsiiMethod: "resetLimit", GoMethod: "ResetLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "used", GoGetter: "Used"},
		},
		func() interface{} {
			j := jsiiProxy_OrgVdcComputeCapacityCpuOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.orgVdc.OrgVdcComputeCapacityMemory",
		reflect.TypeOf((*OrgVdcComputeCapacityMemory)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.orgVdc.OrgVdcComputeCapacityMemoryOutputReference",
		reflect.TypeOf((*OrgVdcComputeCapacityMemoryOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "allocated", GoGetter: "Allocated"},
			_jsii_.MemberProperty{JsiiProperty: "allocatedInput", GoGetter: "AllocatedInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "limit", GoGetter: "Limit"},
			_jsii_.MemberProperty{JsiiProperty: "limitInput", GoGetter: "LimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "reserved", GoGetter: "Reserved"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllocated", GoMethod: "ResetAllocated"},
			_jsii_.MemberMethod{JsiiMethod: "resetLimit", GoMethod: "ResetLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "used", GoGetter: "Used"},
		},
		func() interface{} {
			j := jsiiProxy_OrgVdcComputeCapacityMemoryOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"vcd.orgVdc.OrgVdcComputeCapacityOutputReference",
		reflect.TypeOf((*OrgVdcComputeCapacityOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "cpu", GoGetter: "Cpu"},
			_jsii_.MemberProperty{JsiiProperty: "cpuInput", GoGetter: "CpuInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "memory", GoGetter: "Memory"},
			_jsii_.MemberProperty{JsiiProperty: "memoryInput", GoGetter: "MemoryInput"},
			_jsii_.MemberMethod{JsiiMethod: "putCpu", GoMethod: "PutCpu"},
			_jsii_.MemberMethod{JsiiMethod: "putMemory", GoMethod: "PutMemory"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_OrgVdcComputeCapacityOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.orgVdc.OrgVdcConfig",
		reflect.TypeOf((*OrgVdcConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"vcd.orgVdc.OrgVdcMetadataEntry",
		reflect.TypeOf((*OrgVdcMetadataEntry)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.orgVdc.OrgVdcMetadataEntryList",
		reflect.TypeOf((*OrgVdcMetadataEntryList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_OrgVdcMetadataEntryList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"vcd.orgVdc.OrgVdcMetadataEntryOutputReference",
		reflect.TypeOf((*OrgVdcMetadataEntryOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "isSystem", GoGetter: "IsSystem"},
			_jsii_.MemberProperty{JsiiProperty: "isSystemInput", GoGetter: "IsSystemInput"},
			_jsii_.MemberProperty{JsiiProperty: "key", GoGetter: "Key"},
			_jsii_.MemberProperty{JsiiProperty: "keyInput", GoGetter: "KeyInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsSystem", GoMethod: "ResetIsSystem"},
			_jsii_.MemberMethod{JsiiMethod: "resetKey", GoMethod: "ResetKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetType", GoMethod: "ResetType"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserAccess", GoMethod: "ResetUserAccess"},
			_jsii_.MemberMethod{JsiiMethod: "resetValue", GoMethod: "ResetValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "userAccess", GoGetter: "UserAccess"},
			_jsii_.MemberProperty{JsiiProperty: "userAccessInput", GoGetter: "UserAccessInput"},
			_jsii_.MemberProperty{JsiiProperty: "value", GoGetter: "Value"},
			_jsii_.MemberProperty{JsiiProperty: "valueInput", GoGetter: "ValueInput"},
		},
		func() interface{} {
			j := jsiiProxy_OrgVdcMetadataEntryOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.orgVdc.OrgVdcStorageProfile",
		reflect.TypeOf((*OrgVdcStorageProfile)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.orgVdc.OrgVdcStorageProfileList",
		reflect.TypeOf((*OrgVdcStorageProfileList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_OrgVdcStorageProfileList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"vcd.orgVdc.OrgVdcStorageProfileOutputReference",
		reflect.TypeOf((*OrgVdcStorageProfileOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "default", GoGetter: "Default"},
			_jsii_.MemberProperty{JsiiProperty: "defaultInput", GoGetter: "DefaultInput"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "limit", GoGetter: "Limit"},
			_jsii_.MemberProperty{JsiiProperty: "limitInput", GoGetter: "LimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "storageUsedInMb", GoGetter: "StorageUsedInMb"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_OrgVdcStorageProfileOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
