package vm

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"vcd.vm.Vm",
		reflect.TypeOf((*Vm)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "acceptAllEulas", GoGetter: "AcceptAllEulas"},
			_jsii_.MemberProperty{JsiiProperty: "acceptAllEulasInput", GoGetter: "AcceptAllEulasInput"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "bootImage", GoGetter: "BootImage"},
			_jsii_.MemberProperty{JsiiProperty: "bootImageId", GoGetter: "BootImageId"},
			_jsii_.MemberProperty{JsiiProperty: "bootImageIdInput", GoGetter: "BootImageIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "bootImageInput", GoGetter: "BootImageInput"},
			_jsii_.MemberProperty{JsiiProperty: "catalogName", GoGetter: "CatalogName"},
			_jsii_.MemberProperty{JsiiProperty: "catalogNameInput", GoGetter: "CatalogNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "computerName", GoGetter: "ComputerName"},
			_jsii_.MemberProperty{JsiiProperty: "computerNameInput", GoGetter: "ComputerNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "cpuCores", GoGetter: "CpuCores"},
			_jsii_.MemberProperty{JsiiProperty: "cpuCoresInput", GoGetter: "CpuCoresInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuHotAddEnabled", GoGetter: "CpuHotAddEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "cpuHotAddEnabledInput", GoGetter: "CpuHotAddEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuLimit", GoGetter: "CpuLimit"},
			_jsii_.MemberProperty{JsiiProperty: "cpuLimitInput", GoGetter: "CpuLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuPriority", GoGetter: "CpuPriority"},
			_jsii_.MemberProperty{JsiiProperty: "cpuPriorityInput", GoGetter: "CpuPriorityInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuReservation", GoGetter: "CpuReservation"},
			_jsii_.MemberProperty{JsiiProperty: "cpuReservationInput", GoGetter: "CpuReservationInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpus", GoGetter: "Cpus"},
			_jsii_.MemberProperty{JsiiProperty: "cpuShares", GoGetter: "CpuShares"},
			_jsii_.MemberProperty{JsiiProperty: "cpuSharesInput", GoGetter: "CpuSharesInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpusInput", GoGetter: "CpusInput"},
			_jsii_.MemberProperty{JsiiProperty: "customization", GoGetter: "Customization"},
			_jsii_.MemberProperty{JsiiProperty: "customizationInput", GoGetter: "CustomizationInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "disk", GoGetter: "Disk"},
			_jsii_.MemberProperty{JsiiProperty: "diskInput", GoGetter: "DiskInput"},
			_jsii_.MemberProperty{JsiiProperty: "exposeHardwareVirtualization", GoGetter: "ExposeHardwareVirtualization"},
			_jsii_.MemberProperty{JsiiProperty: "exposeHardwareVirtualizationInput", GoGetter: "ExposeHardwareVirtualizationInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "guestProperties", GoGetter: "GuestProperties"},
			_jsii_.MemberProperty{JsiiProperty: "guestPropertiesInput", GoGetter: "GuestPropertiesInput"},
			_jsii_.MemberProperty{JsiiProperty: "hardwareVersion", GoGetter: "HardwareVersion"},
			_jsii_.MemberProperty{JsiiProperty: "hardwareVersionInput", GoGetter: "HardwareVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "href", GoGetter: "Href"},
			_jsii_.MemberProperty{JsiiProperty: "hrefInput", GoGetter: "HrefInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalDisk", GoGetter: "InternalDisk"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "memory", GoGetter: "Memory"},
			_jsii_.MemberProperty{JsiiProperty: "memoryHotAddEnabled", GoGetter: "MemoryHotAddEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "memoryHotAddEnabledInput", GoGetter: "MemoryHotAddEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryInput", GoGetter: "MemoryInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryLimit", GoGetter: "MemoryLimit"},
			_jsii_.MemberProperty{JsiiProperty: "memoryLimitInput", GoGetter: "MemoryLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryPriority", GoGetter: "MemoryPriority"},
			_jsii_.MemberProperty{JsiiProperty: "memoryPriorityInput", GoGetter: "MemoryPriorityInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryReservation", GoGetter: "MemoryReservation"},
			_jsii_.MemberProperty{JsiiProperty: "memoryReservationInput", GoGetter: "MemoryReservationInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryShares", GoGetter: "MemoryShares"},
			_jsii_.MemberProperty{JsiiProperty: "memorySharesInput", GoGetter: "MemorySharesInput"},
			_jsii_.MemberProperty{JsiiProperty: "metadata", GoGetter: "Metadata"},
			_jsii_.MemberProperty{JsiiProperty: "metadataEntry", GoGetter: "MetadataEntry"},
			_jsii_.MemberProperty{JsiiProperty: "metadataEntryInput", GoGetter: "MetadataEntryInput"},
			_jsii_.MemberProperty{JsiiProperty: "metadataInput", GoGetter: "MetadataInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "network", GoGetter: "Network"},
			_jsii_.MemberProperty{JsiiProperty: "networkDhcpWaitSeconds", GoGetter: "NetworkDhcpWaitSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "networkDhcpWaitSecondsInput", GoGetter: "NetworkDhcpWaitSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkInput", GoGetter: "NetworkInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "org", GoGetter: "Org"},
			_jsii_.MemberProperty{JsiiProperty: "orgInput", GoGetter: "OrgInput"},
			_jsii_.MemberProperty{JsiiProperty: "osType", GoGetter: "OsType"},
			_jsii_.MemberProperty{JsiiProperty: "osTypeInput", GoGetter: "OsTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "overrideTemplateDisk", GoGetter: "OverrideTemplateDisk"},
			_jsii_.MemberProperty{JsiiProperty: "overrideTemplateDiskInput", GoGetter: "OverrideTemplateDiskInput"},
			_jsii_.MemberProperty{JsiiProperty: "placementPolicyId", GoGetter: "PlacementPolicyId"},
			_jsii_.MemberProperty{JsiiProperty: "placementPolicyIdInput", GoGetter: "PlacementPolicyIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "powerOn", GoGetter: "PowerOn"},
			_jsii_.MemberProperty{JsiiProperty: "powerOnInput", GoGetter: "PowerOnInput"},
			_jsii_.MemberProperty{JsiiProperty: "preventUpdatePowerOff", GoGetter: "PreventUpdatePowerOff"},
			_jsii_.MemberProperty{JsiiProperty: "preventUpdatePowerOffInput", GoGetter: "PreventUpdatePowerOffInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putCustomization", GoMethod: "PutCustomization"},
			_jsii_.MemberMethod{JsiiMethod: "putDisk", GoMethod: "PutDisk"},
			_jsii_.MemberMethod{JsiiMethod: "putMetadataEntry", GoMethod: "PutMetadataEntry"},
			_jsii_.MemberMethod{JsiiMethod: "putNetwork", GoMethod: "PutNetwork"},
			_jsii_.MemberMethod{JsiiMethod: "putOverrideTemplateDisk", GoMethod: "PutOverrideTemplateDisk"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAcceptAllEulas", GoMethod: "ResetAcceptAllEulas"},
			_jsii_.MemberMethod{JsiiMethod: "resetBootImage", GoMethod: "ResetBootImage"},
			_jsii_.MemberMethod{JsiiMethod: "resetBootImageId", GoMethod: "ResetBootImageId"},
			_jsii_.MemberMethod{JsiiMethod: "resetCatalogName", GoMethod: "ResetCatalogName"},
			_jsii_.MemberMethod{JsiiMethod: "resetComputerName", GoMethod: "ResetComputerName"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuCores", GoMethod: "ResetCpuCores"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuHotAddEnabled", GoMethod: "ResetCpuHotAddEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuLimit", GoMethod: "ResetCpuLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuPriority", GoMethod: "ResetCpuPriority"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuReservation", GoMethod: "ResetCpuReservation"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpus", GoMethod: "ResetCpus"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuShares", GoMethod: "ResetCpuShares"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomization", GoMethod: "ResetCustomization"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisk", GoMethod: "ResetDisk"},
			_jsii_.MemberMethod{JsiiMethod: "resetExposeHardwareVirtualization", GoMethod: "ResetExposeHardwareVirtualization"},
			_jsii_.MemberMethod{JsiiMethod: "resetGuestProperties", GoMethod: "ResetGuestProperties"},
			_jsii_.MemberMethod{JsiiMethod: "resetHardwareVersion", GoMethod: "ResetHardwareVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetHref", GoMethod: "ResetHref"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemory", GoMethod: "ResetMemory"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryHotAddEnabled", GoMethod: "ResetMemoryHotAddEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryLimit", GoMethod: "ResetMemoryLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryPriority", GoMethod: "ResetMemoryPriority"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryReservation", GoMethod: "ResetMemoryReservation"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryShares", GoMethod: "ResetMemoryShares"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetadata", GoMethod: "ResetMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "resetMetadataEntry", GoMethod: "ResetMetadataEntry"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetwork", GoMethod: "ResetNetwork"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkDhcpWaitSeconds", GoMethod: "ResetNetworkDhcpWaitSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetOrg", GoMethod: "ResetOrg"},
			_jsii_.MemberMethod{JsiiMethod: "resetOsType", GoMethod: "ResetOsType"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideTemplateDisk", GoMethod: "ResetOverrideTemplateDisk"},
			_jsii_.MemberMethod{JsiiMethod: "resetPlacementPolicyId", GoMethod: "ResetPlacementPolicyId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPowerOn", GoMethod: "ResetPowerOn"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreventUpdatePowerOff", GoMethod: "ResetPreventUpdatePowerOff"},
			_jsii_.MemberMethod{JsiiMethod: "resetSecurityTags", GoMethod: "ResetSecurityTags"},
			_jsii_.MemberMethod{JsiiMethod: "resetSizingPolicyId", GoMethod: "ResetSizingPolicyId"},
			_jsii_.MemberMethod{JsiiMethod: "resetStorageProfile", GoMethod: "ResetStorageProfile"},
			_jsii_.MemberMethod{JsiiMethod: "resetTemplateName", GoMethod: "ResetTemplateName"},
			_jsii_.MemberMethod{JsiiMethod: "resetVappName", GoMethod: "ResetVappName"},
			_jsii_.MemberMethod{JsiiMethod: "resetVappTemplateId", GoMethod: "ResetVappTemplateId"},
			_jsii_.MemberMethod{JsiiMethod: "resetVdc", GoMethod: "ResetVdc"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmNameInTemplate", GoMethod: "ResetVmNameInTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "securityTags", GoGetter: "SecurityTags"},
			_jsii_.MemberProperty{JsiiProperty: "securityTagsInput", GoGetter: "SecurityTagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "sizingPolicyId", GoGetter: "SizingPolicyId"},
			_jsii_.MemberProperty{JsiiProperty: "sizingPolicyIdInput", GoGetter: "SizingPolicyIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "status", GoGetter: "Status"},
			_jsii_.MemberProperty{JsiiProperty: "statusText", GoGetter: "StatusText"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfile", GoGetter: "StorageProfile"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfileInput", GoGetter: "StorageProfileInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "templateName", GoGetter: "TemplateName"},
			_jsii_.MemberProperty{JsiiProperty: "templateNameInput", GoGetter: "TemplateNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "vappName", GoGetter: "VappName"},
			_jsii_.MemberProperty{JsiiProperty: "vappNameInput", GoGetter: "VappNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "vappTemplateId", GoGetter: "VappTemplateId"},
			_jsii_.MemberProperty{JsiiProperty: "vappTemplateIdInput", GoGetter: "VappTemplateIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "vdc", GoGetter: "Vdc"},
			_jsii_.MemberProperty{JsiiProperty: "vdcInput", GoGetter: "VdcInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmNameInTemplate", GoGetter: "VmNameInTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "vmNameInTemplateInput", GoGetter: "VmNameInTemplateInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmType", GoGetter: "VmType"},
		},
		func() interface{} {
			j := jsiiProxy_Vm{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.vm.VmConfig",
		reflect.TypeOf((*VmConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"vcd.vm.VmCustomization",
		reflect.TypeOf((*VmCustomization)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmCustomizationOutputReference",
		reflect.TypeOf((*VmCustomizationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "adminPassword", GoGetter: "AdminPassword"},
			_jsii_.MemberProperty{JsiiProperty: "adminPasswordInput", GoGetter: "AdminPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "allowLocalAdminPassword", GoGetter: "AllowLocalAdminPassword"},
			_jsii_.MemberProperty{JsiiProperty: "allowLocalAdminPasswordInput", GoGetter: "AllowLocalAdminPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "autoGeneratePassword", GoGetter: "AutoGeneratePassword"},
			_jsii_.MemberProperty{JsiiProperty: "autoGeneratePasswordInput", GoGetter: "AutoGeneratePasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "changeSid", GoGetter: "ChangeSid"},
			_jsii_.MemberProperty{JsiiProperty: "changeSidInput", GoGetter: "ChangeSidInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "force", GoGetter: "Force"},
			_jsii_.MemberProperty{JsiiProperty: "forceInput", GoGetter: "ForceInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "initscript", GoGetter: "Initscript"},
			_jsii_.MemberProperty{JsiiProperty: "initscriptInput", GoGetter: "InitscriptInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomain", GoGetter: "JoinDomain"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainAccountOu", GoGetter: "JoinDomainAccountOu"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainAccountOuInput", GoGetter: "JoinDomainAccountOuInput"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainInput", GoGetter: "JoinDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainName", GoGetter: "JoinDomainName"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainNameInput", GoGetter: "JoinDomainNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainPassword", GoGetter: "JoinDomainPassword"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainPasswordInput", GoGetter: "JoinDomainPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainUser", GoGetter: "JoinDomainUser"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainUserInput", GoGetter: "JoinDomainUserInput"},
			_jsii_.MemberProperty{JsiiProperty: "joinOrgDomain", GoGetter: "JoinOrgDomain"},
			_jsii_.MemberProperty{JsiiProperty: "joinOrgDomainInput", GoGetter: "JoinOrgDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "mustChangePasswordOnFirstLogin", GoGetter: "MustChangePasswordOnFirstLogin"},
			_jsii_.MemberProperty{JsiiProperty: "mustChangePasswordOnFirstLoginInput", GoGetter: "MustChangePasswordOnFirstLoginInput"},
			_jsii_.MemberProperty{JsiiProperty: "numberOfAutoLogons", GoGetter: "NumberOfAutoLogons"},
			_jsii_.MemberProperty{JsiiProperty: "numberOfAutoLogonsInput", GoGetter: "NumberOfAutoLogonsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAdminPassword", GoMethod: "ResetAdminPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowLocalAdminPassword", GoMethod: "ResetAllowLocalAdminPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutoGeneratePassword", GoMethod: "ResetAutoGeneratePassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetChangeSid", GoMethod: "ResetChangeSid"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetForce", GoMethod: "ResetForce"},
			_jsii_.MemberMethod{JsiiMethod: "resetInitscript", GoMethod: "ResetInitscript"},
			_jsii_.MemberMethod{JsiiMethod: "resetJoinDomain", GoMethod: "ResetJoinDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetJoinDomainAccountOu", GoMethod: "ResetJoinDomainAccountOu"},
			_jsii_.MemberMethod{JsiiMethod: "resetJoinDomainName", GoMethod: "ResetJoinDomainName"},
			_jsii_.MemberMethod{JsiiMethod: "resetJoinDomainPassword", GoMethod: "ResetJoinDomainPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetJoinDomainUser", GoMethod: "ResetJoinDomainUser"},
			_jsii_.MemberMethod{JsiiMethod: "resetJoinOrgDomain", GoMethod: "ResetJoinOrgDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetMustChangePasswordOnFirstLogin", GoMethod: "ResetMustChangePasswordOnFirstLogin"},
			_jsii_.MemberMethod{JsiiMethod: "resetNumberOfAutoLogons", GoMethod: "ResetNumberOfAutoLogons"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VmCustomizationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.vm.VmDisk",
		reflect.TypeOf((*VmDisk)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmDiskList",
		reflect.TypeOf((*VmDiskList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VmDiskList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmDiskOutputReference",
		reflect.TypeOf((*VmDiskOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "busNumber", GoGetter: "BusNumber"},
			_jsii_.MemberProperty{JsiiProperty: "busNumberInput", GoGetter: "BusNumberInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "sizeInMb", GoGetter: "SizeInMb"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "unitNumber", GoGetter: "UnitNumber"},
			_jsii_.MemberProperty{JsiiProperty: "unitNumberInput", GoGetter: "UnitNumberInput"},
		},
		func() interface{} {
			j := jsiiProxy_VmDiskOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.vm.VmInternalDisk",
		reflect.TypeOf((*VmInternalDisk)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmInternalDiskList",
		reflect.TypeOf((*VmInternalDiskList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VmInternalDiskList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmInternalDiskOutputReference",
		reflect.TypeOf((*VmInternalDiskOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "busNumber", GoGetter: "BusNumber"},
			_jsii_.MemberProperty{JsiiProperty: "busType", GoGetter: "BusType"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "diskId", GoGetter: "DiskId"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "iops", GoGetter: "Iops"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "sizeInMb", GoGetter: "SizeInMb"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfile", GoGetter: "StorageProfile"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "thinProvisioned", GoGetter: "ThinProvisioned"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "unitNumber", GoGetter: "UnitNumber"},
		},
		func() interface{} {
			j := jsiiProxy_VmInternalDiskOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.vm.VmMetadataEntry",
		reflect.TypeOf((*VmMetadataEntry)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmMetadataEntryList",
		reflect.TypeOf((*VmMetadataEntryList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VmMetadataEntryList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmMetadataEntryOutputReference",
		reflect.TypeOf((*VmMetadataEntryOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "isSystem", GoGetter: "IsSystem"},
			_jsii_.MemberProperty{JsiiProperty: "isSystemInput", GoGetter: "IsSystemInput"},
			_jsii_.MemberProperty{JsiiProperty: "key", GoGetter: "Key"},
			_jsii_.MemberProperty{JsiiProperty: "keyInput", GoGetter: "KeyInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsSystem", GoMethod: "ResetIsSystem"},
			_jsii_.MemberMethod{JsiiMethod: "resetKey", GoMethod: "ResetKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetType", GoMethod: "ResetType"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserAccess", GoMethod: "ResetUserAccess"},
			_jsii_.MemberMethod{JsiiMethod: "resetValue", GoMethod: "ResetValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "userAccess", GoGetter: "UserAccess"},
			_jsii_.MemberProperty{JsiiProperty: "userAccessInput", GoGetter: "UserAccessInput"},
			_jsii_.MemberProperty{JsiiProperty: "value", GoGetter: "Value"},
			_jsii_.MemberProperty{JsiiProperty: "valueInput", GoGetter: "ValueInput"},
		},
		func() interface{} {
			j := jsiiProxy_VmMetadataEntryOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.vm.VmNetwork",
		reflect.TypeOf((*VmNetwork)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmNetworkList",
		reflect.TypeOf((*VmNetworkList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VmNetworkList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmNetworkOutputReference",
		reflect.TypeOf((*VmNetworkOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "adapterType", GoGetter: "AdapterType"},
			_jsii_.MemberProperty{JsiiProperty: "adapterTypeInput", GoGetter: "AdapterTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "connected", GoGetter: "Connected"},
			_jsii_.MemberProperty{JsiiProperty: "connectedInput", GoGetter: "ConnectedInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ip", GoGetter: "Ip"},
			_jsii_.MemberProperty{JsiiProperty: "ipAllocationMode", GoGetter: "IpAllocationMode"},
			_jsii_.MemberProperty{JsiiProperty: "ipAllocationModeInput", GoGetter: "IpAllocationModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipInput", GoGetter: "IpInput"},
			_jsii_.MemberProperty{JsiiProperty: "isPrimary", GoGetter: "IsPrimary"},
			_jsii_.MemberProperty{JsiiProperty: "isPrimaryInput", GoGetter: "IsPrimaryInput"},
			_jsii_.MemberProperty{JsiiProperty: "mac", GoGetter: "Mac"},
			_jsii_.MemberProperty{JsiiProperty: "macInput", GoGetter: "MacInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAdapterType", GoMethod: "ResetAdapterType"},
			_jsii_.MemberMethod{JsiiMethod: "resetConnected", GoMethod: "ResetConnected"},
			_jsii_.MemberMethod{JsiiMethod: "resetIp", GoMethod: "ResetIp"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpAllocationMode", GoMethod: "ResetIpAllocationMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsPrimary", GoMethod: "ResetIsPrimary"},
			_jsii_.MemberMethod{JsiiMethod: "resetMac", GoMethod: "ResetMac"},
			_jsii_.MemberMethod{JsiiMethod: "resetName", GoMethod: "ResetName"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
		},
		func() interface{} {
			j := jsiiProxy_VmNetworkOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"vcd.vm.VmOverrideTemplateDisk",
		reflect.TypeOf((*VmOverrideTemplateDisk)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmOverrideTemplateDiskList",
		reflect.TypeOf((*VmOverrideTemplateDiskList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VmOverrideTemplateDiskList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"vcd.vm.VmOverrideTemplateDiskOutputReference",
		reflect.TypeOf((*VmOverrideTemplateDiskOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "busNumber", GoGetter: "BusNumber"},
			_jsii_.MemberProperty{JsiiProperty: "busNumberInput", GoGetter: "BusNumberInput"},
			_jsii_.MemberProperty{JsiiProperty: "busType", GoGetter: "BusType"},
			_jsii_.MemberProperty{JsiiProperty: "busTypeInput", GoGetter: "BusTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "iops", GoGetter: "Iops"},
			_jsii_.MemberProperty{JsiiProperty: "iopsInput", GoGetter: "IopsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetIops", GoMethod: "ResetIops"},
			_jsii_.MemberMethod{JsiiMethod: "resetStorageProfile", GoMethod: "ResetStorageProfile"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "sizeInMb", GoGetter: "SizeInMb"},
			_jsii_.MemberProperty{JsiiProperty: "sizeInMbInput", GoGetter: "SizeInMbInput"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfile", GoGetter: "StorageProfile"},
			_jsii_.MemberProperty{JsiiProperty: "storageProfileInput", GoGetter: "StorageProfileInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "unitNumber", GoGetter: "UnitNumber"},
			_jsii_.MemberProperty{JsiiProperty: "unitNumberInput", GoGetter: "UnitNumberInput"},
		},
		func() interface{} {
			j := jsiiProxy_VmOverrideTemplateDiskOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
